#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# Not encouraged by Gradle and can produce weird results. Wait for isolated projects instead.
org.gradle.configureondemand=false

# Enable caching between builds.
org.gradle.caching=true

mavenGroup=io.github.openMF
defaultVersion=1.0.0
desc=Kotlin Multiplatform passcode authentication library providing UI and logic for passcode creation, verification, and management across Android, iOS, Desktop, and Web using Compose Multiplatform.
license=MIT License
creationYear=2025
githubRepo=openMF/mifos-passcode-cmp