/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/mifos-passcode-cmp/blob/development/LICENSE
 */
import org.gradle.api.tasks.compile.AbstractCompile

plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
}

// Plugin version. Released in lockstep with the mifos-authenticator-passcode
// library: bumping the lib's published version requires bumping this string,
// and the build-time codegen (below) bakes it into BuildConfig.kt so the
// runtime URL resolution always points at the matching `v$LIBRARY_VERSION`
// git tag in the openMF repo.
group = "org.mifos.authenticator"
version = "0.1.0"

repositories {
    mavenCentral()
    gradlePluginPortal()
}

gradlePlugin {
    plugins {
        register("mifosL10n") {
            id = "org.mifos.authenticator.l10n"
            implementationClass = "org.mifos.authenticator.l10n.MifosL10nPlugin"
            displayName = "Mifos passcode l10n templates downloader"
            description = "Downloads localized passcode strings from the mifos-passcode-cmp " +
                "repository's l10n-templates/passcode/ tree and merges them into the consumer's " +
                "Compose Multiplatform composeResources/values-XX/strings.xml files. Pinned " +
                "to the matching library version via a baked-in BuildConfig constant."
        }
    }
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

// Build-time codegen: emit src/generated/.../BuildConfig.kt with LIBRARY_VERSION = "<plugin version>".
val generateBuildConfig = tasks.register("generateBuildConfig") {
    val outputDir = layout.buildDirectory.dir("generated/source/buildConfig/kotlin/main")
    val versionToWrite = project.version.toString()

    inputs.property("version", versionToWrite)
    outputs.dir(outputDir)

    doLast {
        val out = outputDir.get().file("org/mifos/authenticator/l10n/BuildConfig.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            """
            // Generated by build.gradle.kts; do not edit.
            package org.mifos.authenticator.l10n

            internal const val LIBRARY_VERSION = "$versionToWrite"
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    sourceSets["main"].kotlin.srcDir(generateBuildConfig.map { it.outputs.files })
}

tasks.withType<AbstractCompile>().configureEach {
    dependsOn(generateBuildConfig)
}
