#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# Not encouraged by Gradle and can produce weird results. Wait for isolated projects instead.
org.gradle.configureondemand=false

# Enable caching between builds.
org.gradle.caching=true

mavenGroup=io.github.openmf
defaultVersion=2.0.1
desc=Kotlin Multiplatform library that provides a unified API for biometric authentication (e.g., fingerprint, face ID) and device credentials (e.g., PIN, password) across Android, iOS, Desktop and Web platforms. It simplifies the process of integrating platform-specific authentication mechanisms into your application, allowing you to write a single codebase for user authentication.
license=MIT License
creationYear=2026
githubRepo=openMF/mifos-passcode-cmp
