name: Publish
on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Publish to MavenCentral with Debug Logs
        run: |
          echo "Starting Publish to MavenCentral"
          # Write the base64-encoded GPG key to a file
          echo "$ORG_GRADLE_PROJECT_signingInMemoryKey" > encoded.key
          encoded_length=$(wc -c < encoded.key)
          echo "Encoded key length: $encoded_length"

          # Decode the key (macOS uses -D for decode)
          base64 -D -i encoded.key -o decoded.key || { echo "Error decoding base64 key"; exit 1; }
          decoded_length=$(wc -c < decoded.key)
          echo "Decoded key length: $decoded_length"

          # Export the decoded key for Gradle's in-memory signing
          export ORG_GRADLE_PROJECT_signingInMemoryKey="$(cat decoded.key)"
          echo "Exported signingInMemoryKey length: $(echo "$ORG_GRADLE_PROJECT_signingInMemoryKey" | wc -c)"

          # Run Gradle with detailed logs and disable configuration cache
          ./gradlew publishToMavenCentral --no-configuration-cache --info
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
